name: LeetCode Verify CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
    - uses: actions/checkout@v3
    - name: Verify each JS File
      run: |
          files=$(git diff --name-only HEAD^ HEAD | grep '\.js$')
          for file in $files; do
            ./scripts/runner.sh "$file"
          done
